### ISSUE TITLE
LCD Shield issues

### ISSUE THREAD

**Issue by Guddler** [prswan/arduino-mega-ict#2]
Primary issue is that of my shield not working :)

I ordered an LCD Shield from hobbytronics.co.uk (http://www.hobbytronics.co.uk/arduino-lcd-keypad-shield). I thought it should just be a clone or copy of v1.0 of the SwainSmart one but when I got it the only key that would work was right. The shield is by DFRobotics: http://www.dfrobot.com/wiki/index.php/LCD_KeyPad_Shield_For_Arduino_SKU:_DFR0009

On investigation, that key's analogue value is 0 so no surprise that one worked. It appears that my shield has different values even to the v1 of the DFRobotics shield (despite that being what it is!). It is easy enough to work around by using a #define to add an alternative set of values and switch them at compile time.

I'm not sure if I should be modifying the DFKey library? It seems like the answer to that is no?

The other thing is that the wiki examples, although coded differently suggest it being a good idea to test for NO_KEY first since most of the time that will be true. Since this will especially be true when we are giving the ICT things to do, maybe we should do that?

I have commits for both of these things and can create a pull request, just not sure about the library situation.

**Comment by prswan** [comment]
Feel free to create a pull request that makes the key values definable but please leave the defaults matching the Sain. If the wiring is the same on your shield but only the resistor values are different, then you could also change the resistor values to match the Sain.

**Comment by Guddler** [comment]
OK, given the resistors are underneath the display, the easiest thing for me to do is make the code change, so I'll do that. I think if I'm going to start modifying library code that is standard from the manufacturer then I should create an ICT_Key library rather than mess with DFKey. That will save any confusion and I don't see a problem given there's no license attribution in the supplied library.

Will leave this open until I've done it.

**Comment by prswan** [comment]
If it's simple enough to just add a #define control for the values for your shield then that's OK rather than creating a whole new lib just for that change if that's the only change :)

**Comment by Guddler** [comment]
OK, I'm struggling to find a way to do this without it being a pain for everyone else. The obvious answer is a #define - something like #define ALT_VALUES (with a better name because there will surely be other values needed for other versions of the shield - the v1.1 is not so common as the v1).

The problem is though that even if I don't define that when I check it in to the project SOMEONE will sooner or later.

If someone is using Visual Studio or Atmel Studio then it's easy enough as that define can be placed in the project settings of the IDE but I can't see a way to do that for the Arduino IDE which means that anyone not using the above will run into the define problem.

This should be so simple :D

**Comment by prswan** [comment]
You need to add your set of defines controlled by another define, e.g. 
#ifdef MY_LCD_SHIELD
#define "my LCD analogue values"
#else
#define "sain analogue values"
#endif

Then you can update your hardware/platform.txt to add a "-DMY_LCD_SHIELD" to the compiler flags that will set it for everything you build.
Paul.
