### ISSUE TITLE
Asteroids code preview

### ISSUE THREAD

**Issue by Guddler** [prswan/arduino-mega-ict#4]
Not really an issue this, but I don't think GitHub has different issue types?

Anyway, not urgent, but when you get a minute could you have a nose at the Asteroids files I've added and let me know if there are any style changes you're likely to want or if I have made any glaringly obvious mistakes?

https://github.com/Guddler/arduino-mega-ict/tree/asteroids/libraries/C6502Cpu

I've not done a PR yet as it's very much a WIP and my ICT was not working (A11 not drivable due to an open resistor) but Set 2 (per mame) is defined and looks like it works OK, as are the inputs, outputs and ram. I have a Meteroids on the bench so will likely add that variant as well. I've also split the base game to allow for Deluxe and Lunar Lander to be put in later.

**Comment by prswan** [comment]
Looking reasonable so far. Minor comments are easier to add line-by-line in the PR code review. I think I've been using no tabs and 4 spaces per indent :)

**Comment by prswan** [comment]
I made some bug fixes I found to the standard 6502 whilst I was doing the clock master version, when you get a chance can you confirm it works OK with your Asteroids port?
https://github.com/prswan/arduino-mega-ict/tree/6502_clock_master
Thanks,
Paul.
